[package]
name = "polkaregistry"
version = "0.1.0"
authors = ["Wei Tang <wei@that.world>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Polkaregistry command line utility."

[dependencies]
