[package]
name = "polkaregistry"
version = "0.1.0"
authors = ["Wei Tang <wei@that.world>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Polkaregistry command line utility."

[dependencies]
structopt = "0.3"
sp-core = "3.0"
sp-keystore = "0.9"
sc-keystore = "3.0"
directories = "3.0"